import { Fragment } from "react"
import Head from "next/head"
import { useRouter } from "next/router";
import Stack from "@mui/material/Stack";
import List from "@mui/material/List";
import ListItem from "@mui/material/ListItem";
import Divider from "@mui/material/Divider";
import ListItemButton from "@mui/material/ListItemButton";
import ListItemAvatar from "@mui/material/ListItemAvatar";
import ListItemText from "@mui/material/ListItemText";
import Typography from "@mui/material/Typography";

export default function MainApp() {
    const router = useRouter();

    return (
        <Fragment>
            <Head>
                <title>Whatsapp clone</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Fragment>
                <Stack component="article" direction="row">
                    <List component="aside" sx={{ width: "400px" }}>
                        <ListItem
                            disablePadding
                            secondaryAction={
                                <Typography
                                    sx={{
                                        fontWeight: "300",
                                        fontSize: "12px"
                                    }}
                                >
                                    2022/11/22
                                </Typography>
                            }
                        >
                            <ListItemButton>
                                <ListItemAvatar></ListItemAvatar>
                                <ListItemText primary="Rasuwan Kalhara" secondary="Hello world" />
                            </ListItemButton>
                        </ListItem>
                        <ListItem
                            disablePadding
                            secondaryAction={
                                <Typography
                                    sx={{
                                        fontWeight: "300",
                                        fontSize: "12px"
                                    }}
                                >
                                    Yesterday
                                </Typography>
                            }
                        >
                            <ListItemButton>
                                <ListItemAvatar></ListItemAvatar>
                                <ListItemText primary="Kate Bush" secondary="Hola !" />
                            </ListItemButton>
                        </ListItem>
                    </List>
                </Stack>
            </Fragment>
        </Fragment>
    )
}