import { Fragment } from "react";
import Head from "next/head";
import Stack from "@mui/material/Stack";
import AppBar from "@mui/material/AppBar";
import Toolbar from "@mui/material/Toolbar";

export default function MainApp() {
    return (
        <Fragment>
            <Head>
                <title>Whatsapp clone</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Fragment>
                <Stack component="article" direction="row">
                    
                </Stack>
            </Fragment>
        </Fragment>
    )
}