import Head from 'next/head'
import PageLayout from '@/components/page-layout'
import Container from '@mui/material/Container';
import WelcomeCard from '@/components/welcome-card/card';
import useMediaQuery from "@mui/material/useMediaQuery";

export default function Home() {
  const isSmallDevice = useMediaQuery("(max-width: 500px)");
  return (
    <>
      <Head>
        <title>Welcome to whatsapp clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout>
        <Container 
          maxWidth="md" 
          disableGutters={isSmallDevice ? true : false}
        >
          <WelcomeCard />
        </Container>
      </PageLayout>
    </>
  )
}
